# Generated by Django 4.0.3 on 2022-03-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.foods')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
