# Generated by Django 4.0.3 on 2022-03-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='food_id',
            new_name='food',
        ),
    ]
