# Generated by Django 4.0.3 on 2022-03-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_food_id_orders_food'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('id', 'food')},
        ),
    ]
