# Generated by Django 4.0.3 on 2022-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='Rice', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(default='main_dish', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='food',
            field=models.IntegerField(default=1),
        ),
    ]
