# Generated by Django 4.0.3 on 2022-03-03 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_name_orders_price_orders_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
