# Generated by Django 4.0.3 on 2022-03-04 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
